name: Deploy tmc-langs-rust

on:
  push:
    tags:
      - "rust-v*"

jobs:
  build_and_upload:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Enable Docker IPv6
        run: |
          echo '{ "ipv6": true }' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl reload docker
      - uses: actions/checkout@v1
      - name: Load env
        run: |
          source ./env
          echo ::set-env name=RUST_CLI_NAME::${RUST_CLI_NAME}
          echo ::set-env name=RUST_CLI_VER::${RUST_CLI_VER}
          echo ::set-env name=RUST_CLI_URL::${RUST_CLI_URL}
      # - name: Install gcloud
      #   run: |
      #     curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
      #     mkdir -p "$HOME/gcloud" \
      #       && tar -C "$HOME/gcloud" -xvf /tmp/google-cloud-sdk.tar.gz \
      #       && "$HOME/gcloud/google-cloud-sdk/install.sh"
      #     export PATH="$PATH":"$HOME/gcloud/google-cloud-sdk/bin"
      - name: Authenticate to Google Cloud
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo Authenticating to Google Cloud
          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          if gcloud auth configure-docker -q; then
              echo "Authenticated to Google Cloud..."
          else
              echo "Authentication to Google Cloud failed. Exiting..."
              exit 1
          fi
      - name: Building image
        run: |
          docker build . -t "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:${{ env.RUST_CLI_VER }}" --build-arg "RUST_CLI_VER=${{ env.RUST_CLI_URL }}"
      - name: Pushing image
        run: |
          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:${{ env.RUST_CLI_VER }}"
          docker tag "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:${{ env.RUST_CLI_VER }}" "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:latest"
          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:latest"
