on: [push]

jobs:
  build_and_upload:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Enable Docker IPv6
        run: |
          echo '{ "ipv6": true }' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl reload docker
      - uses: actions/checkout@v1
      - name: Build Docker image
        id: build_docker_image
        run: |
          cd tmc-langs-rust && bash build.sh
          source ../env
          echo ::set-output name=RUST_CLI_NAME::${RUST_CLI_NAME}
          echo ::set-output name=RUST_CLI_VER::${RUST_CLI_VER}
      - uses: RafikFarhad/push-to-gcr-github-action@v1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: eu.gcr.io
          project_name: moocfi
          image_name: ${{ steps.build_docker_image.outputs.RUST_CLI_NAME }}
          image_tag: ${{ steps.build_docker_image.outputs.RUST_CLI_VER }}
          dockerfile: ./tmc-langs-rust/Dockerfile
