name: Deploy csharp image

on:
  push:
    tags:
      - "csharp-v*"

jobs:
  build_and_upload:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Enable Docker IPv6
        run: |
          echo '{ "ipv6": true }' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl reload docker
      - uses: actions/checkout@v1
      - name: Load env
        run: |
          source ./env
      - uses: RafikFarhad/push-to-gcr-github-action@v1
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          registry: eu.gcr.io
          project_name: moocfi-public
          image_name: tmc-sandbox-csharp
          image_tag: latest
          context: ./csharp
          dockerfile: ./csharp/Dockerfile
