name: Deploy tmc-langs-rust

on:
  push:
    tags:
      - "rust-v*"

jobs:
  build_and_upload:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Enable Docker IPv6
        run: |
          echo '{ "ipv6": true }' | sudo tee -a /etc/docker/daemon.json
          sudo systemctl reload docker
      - uses: actions/checkout@v1
      - name: Authenticate to Google Cloud
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        run: |
          echo Authenticating to Google Cloud
          echo $GCLOUD_SERVICE_KEY | python -m base64 -d > /tmp/key.json
          gcloud auth activate-service-account --key-file=/tmp/key.json
          if gcloud auth configure-docker -q; then
              echo "Authenticated to Google Cloud..."
          else
              echo "Authentication to Google Cloud failed. Exiting..."
              exit 1
          fi
      - name: Building image
        run: |
          source ./env
          cd tmc-langs-rust
          docker build . -t "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:$RUST_CLI_VER" --build-arg "RUST_CLI_URL=$RUST_CLI_URL"
          cd ..
      - name: Pushing image
        run: |
          source ./env
          cd tmc-langs-rust
          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:$RUST_CLI_VER"
          docker tag "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:$RUST_CLI_VER" "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:latest"
          docker push "eu.gcr.io/moocfi-public/tmc-sandbox-tmc-langs-rust:latest"
          cd ..
